Rdiscount is missing
altoros.github.com$ jekyll --server
Configuration from /media/TRASH/projects/Altoros/altoros.github.com/_config.yml
Building site: /media/TRASH/projects/Altoros/altoros.github.com -> /media/TRASH/projects/Altoros/altoros.github.com/_site
You are missing a library required for Markdown. Please run:
  $ [sudo] gem install rdiscount




ERROR: YOUR SITE COULD NOT BE BUILT:
------------------------------------
Missing dependency: rdiscount